---

# ----------------------  ATD Fabric Common Settings ---------------------- #

# Fabric name
fabric_name: ATD_FABRIC

# Custom Structure Configuration Prefixes

custom_structured_configuration_prefix:
  - "custom_structured_configuration_"
  - "custom_structured_configuration_host_"

# EOS validate state settings
validation_mode_loose: true

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# # Cloud Vision servers
# cvp_instance_ips:
#   - 192.168.0.5

# # CVP ingest key
# cvp_ingestauth_key: "atd-lab"

#Terminattr configuration
daemon_terminattr:
  cvaddrs:
    - 192.168.0.5:9910
  cvauth:
    method: key
    key: "atd-lab"
  disable_aaa: true
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  # cvvrf: default

# Enable Multi-Agent mode
service_routing_protocols_model: multi-agent

# Default BGP settings (for items not found on AVD)
atd_bgp_defaults:
  # - 'update wait-for-convergence'
  # - 'update wait-install'
  - 'no bgp default ipv4-unicast'
  - 'distance bgp 20 200 200'

# vARP MAC address
atd_virtual_router_mac_address: 00:1c:73:00:00:34

#Platform MLAG Standards
CEOS_MLAG_Interfaces: ['Ethernet1', 'Ethernet6']

#Platform UPLINK Standards
CEOS_HOST_UPLINK_Interfaces: ['Ethernet1', 'Ethernet2']
CEOS_LEAF_UPLINK_Interfaces: ['Ethernet1', 'Ethernet2']
CEOS_SPINE_UPLINK_Interfaces: ['Ethernet2', 'Ethernet3']
CEOS_CORE_UPLINK_Interfaces: ['Ethernet2', 'Ethernet3']
CEOS_UPLINK_SWITCH_Interfaces: ['Ethernet4', 'Ethernet4']

# Management VRF Name
mgmt_interface_vrf: default

# DNS information
dns_domain: atd.lab

# NTP Servers

ntp:
  servers:
  - name: 192.168.0.1
    preferred: True
    iburst: true
    local_interface: Management0
    # vrf: MGMT

# RADIUS Config
radius_servers:
  - host: 192.168.0.1
    key: 0207165218120E
    # vrf: MGMT

ip_radius_source_interfaces:
    - name: Management0
      # vrf: MGMT

# AAA Config
aaa_server_groups:
  - name: atds
    type: radius
    servers:
      - server: 192.168.0.1
        # vrf: MGMT

aaa_authentication:
  login:
    default: group atds local

aaa_authorization:
  exec:
    default: group atds local
  commands:
    all_default: local
